name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: main
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@catalogmykit'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}